name: gtk_flutter
description: "Get to know Firebase with Flutter"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  go_router: ^14.1.4
  firebase_core: ^2.32.0
  provider: ^6.1.2
  firebase_ui_auth: ^1.14.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/codelab.png


 